apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-python-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-python-app
  template:
    metadata:
      labels:
        app: my-python-app
    spec:
      containers:
      - name: my-python-app
        image: my-python-app:latest  # Change to match your local image name
        imagePullPolicy: Never  # Force Kubernetes to use the local image
        ports:
        - containerPort: 80
